// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrudBackEndNetCore.Infra.Context;

#nullable disable

namespace SimpleCrudBackEndNetCore.Infra.Migrations
{
    [DbContext(typeof(MicroServiceContext))]
    partial class MicroServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpleCrudBackEndNetCore.Domain.Entities.BrazilianUf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UfCode")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BrazilianUf", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("156c834a-7300-4c7b-8a45-a87df774f900"),
                            Country = "BR",
                            Name = "Rondônia",
                            Uf = "RO",
                            UfCode = 11
                        },
                        new
                        {
                            Id = new Guid("9d9e728f-02bd-4260-95a5-8df655d434d0"),
                            Country = "BR",
                            Name = "Acre",
                            Uf = "AC",
                            UfCode = 12
                        },
                        new
                        {
                            Id = new Guid("085f7465-387a-42d5-a4b5-82e5be81ca7c"),
                            Country = "BR",
                            Name = "Amazonas",
                            Uf = "AM",
                            UfCode = 13
                        },
                        new
                        {
                            Id = new Guid("5192f341-c245-43ed-9567-1ef291d53485"),
                            Country = "BR",
                            Name = "Roraima",
                            Uf = "RR",
                            UfCode = 14
                        },
                        new
                        {
                            Id = new Guid("1207c116-bf8c-41b2-9cfa-b28c42371ff3"),
                            Country = "BR",
                            Name = "Pará",
                            Uf = "PA",
                            UfCode = 15
                        },
                        new
                        {
                            Id = new Guid("790e3c57-596d-46db-98fc-0eb1fbd16516"),
                            Country = "BR",
                            Name = "Amapá",
                            Uf = "AP",
                            UfCode = 16
                        },
                        new
                        {
                            Id = new Guid("e0ff5f07-eec9-4161-9657-5c38dd230dd3"),
                            Country = "BR",
                            Name = "Tocantins",
                            Uf = "TO",
                            UfCode = 17
                        },
                        new
                        {
                            Id = new Guid("425b7437-cf6b-44e3-b708-c0fc869998d6"),
                            Country = "BR",
                            Name = "Maranhão",
                            Uf = "MA",
                            UfCode = 21
                        },
                        new
                        {
                            Id = new Guid("02b4f971-6c52-4d7c-a438-9914c3c6a89b"),
                            Country = "BR",
                            Name = "Piauí",
                            Uf = "PI",
                            UfCode = 22
                        },
                        new
                        {
                            Id = new Guid("4d46948c-c8d6-408b-847a-c98957a3df9f"),
                            Country = "BR",
                            Name = "Ceará",
                            Uf = "CE",
                            UfCode = 23
                        },
                        new
                        {
                            Id = new Guid("6657eaf7-78f1-4f74-85e1-0944594adb22"),
                            Country = "BR",
                            Name = "Rio Grande do Norte",
                            Uf = "RN",
                            UfCode = 24
                        },
                        new
                        {
                            Id = new Guid("276ad231-4150-4bca-9c6d-ff1181746e85"),
                            Country = "BR",
                            Name = "Paraíba",
                            Uf = "PB",
                            UfCode = 25
                        },
                        new
                        {
                            Id = new Guid("2a3c6bf7-4044-445f-8a24-8b938d66c437"),
                            Country = "BR",
                            Name = "Pernambuco",
                            Uf = "PE",
                            UfCode = 26
                        },
                        new
                        {
                            Id = new Guid("cd8c355e-992b-4d84-bbd9-87e388294772"),
                            Country = "BR",
                            Name = "Alagoas",
                            Uf = "AL",
                            UfCode = 27
                        },
                        new
                        {
                            Id = new Guid("e6dc1a76-56ff-4462-a5d5-6b8c5eac2d5c"),
                            Country = "BR",
                            Name = "Sergipe",
                            Uf = "SE",
                            UfCode = 28
                        },
                        new
                        {
                            Id = new Guid("217c3406-b20a-4224-a243-94549accfbe3"),
                            Country = "BR",
                            Name = "Bahia",
                            Uf = "BA",
                            UfCode = 29
                        },
                        new
                        {
                            Id = new Guid("b53b6ae9-87d8-4d9f-94fc-a7e01ca1b6ae"),
                            Country = "BR",
                            Name = "Minas Gerais",
                            Uf = "MG",
                            UfCode = 31
                        },
                        new
                        {
                            Id = new Guid("e8eeba35-7581-4b54-9ee6-6fabd7a5dfb1"),
                            Country = "BR",
                            Name = "Espírito Santo",
                            Uf = "ES",
                            UfCode = 32
                        },
                        new
                        {
                            Id = new Guid("c69ed4b3-54c0-456c-a2e0-56b1300120c4"),
                            Country = "BR",
                            Name = "Rio de Janeiro",
                            Uf = "RJ",
                            UfCode = 33
                        },
                        new
                        {
                            Id = new Guid("52a9afdb-ee0f-4008-875a-45bdb99ca7b0"),
                            Country = "BR",
                            Name = "São Paulo",
                            Uf = "SP",
                            UfCode = 35
                        },
                        new
                        {
                            Id = new Guid("5cdc9548-9638-4b10-ab85-4e0058920110"),
                            Country = "BR",
                            Name = "Paraná",
                            Uf = "PR",
                            UfCode = 41
                        },
                        new
                        {
                            Id = new Guid("a073ffd3-36f0-410b-96de-c26e838e5249"),
                            Country = "BR",
                            Name = "Santa Catarina",
                            Uf = "SC",
                            UfCode = 42
                        },
                        new
                        {
                            Id = new Guid("6c92b0ef-9567-4d54-b0cc-02b7e041d53c"),
                            Country = "BR",
                            Name = "Rio Grande do Sul",
                            Uf = "RS",
                            UfCode = 43
                        },
                        new
                        {
                            Id = new Guid("cd0c5d23-d0cd-4663-a829-79e98a0aa5e0"),
                            Country = "BR",
                            Name = "Mato Grosso do Sul",
                            Uf = "MS",
                            UfCode = 50
                        },
                        new
                        {
                            Id = new Guid("a7b033f0-6376-4c05-8438-899e87b2b71e"),
                            Country = "BR",
                            Name = "Mato Grosso",
                            Uf = "MT",
                            UfCode = 51
                        },
                        new
                        {
                            Id = new Guid("0679caf3-a9f4-4ab5-9872-a74aa69ab97d"),
                            Country = "BR",
                            Name = "Goiás",
                            Uf = "GO",
                            UfCode = 52
                        },
                        new
                        {
                            Id = new Guid("e40c2b75-93ef-47e4-9b9d-ff302d2f04d6"),
                            Country = "BR",
                            Name = "Distrito Federal",
                            Uf = "DF",
                            UfCode = 53
                        });
                });

            modelBuilder.Entity("SimpleCrudBackEndNetCore.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Person", "dbo");
                });

            modelBuilder.Entity("SimpleCrudBackEndNetCore.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("SimpleCrudBackEndNetCore.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BrazilianUfId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("BrazilianUfId");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Nationality");

                            b1.Property<string>("PublicPlace")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PublicPlace");

                            b1.Property<string>("ZoneInformationPostalCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ZoneInformationPostalCode");

                            b1.HasKey("PersonId");

                            b1.HasIndex("BrazilianUfId");

                            b1.ToTable("Person", "dbo");

                            b1.HasOne("SimpleCrudBackEndNetCore.Domain.Entities.BrazilianUf", "BrazilianUf")
                                .WithMany()
                                .HasForeignKey("BrazilianUfId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.Navigation("BrazilianUf");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
